import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'
import '../flow/config.js'

export default function Home() {
  return (
    <div className={styles.container}>

      <Navbar />

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a href="https://developers.flow.com/tools/fcl-js">FCL</a> Next Scaffold
        </h1>

        <p className={styles.description}>
          For the Flow Blockchain
        </p>

        <div className={styles.grid}>
          <a href="https://developers.flow.com/tools/fcl-js/tutorials/flow-app-quickstart" className={styles.card}>
            <h2>FCL Quickstart &rarr;</h2>
            <p>Get up and running.</p>
          </a>

          <a href="https://developers.flow.com/tools/fcl-js/reference/api" className={styles.card}>
            <h2>API Docs &rarr;</h2>
            <p>Dig deeper into FCL.</p>
          </a>

          <a
            href="https://developers.flow.com/tools/fcl-js/reference/discovery"
            className={styles.card}
          >
            <h2>Wallet Discovery &rarr;</h2>
            <p>Integrate wallets.</p>
          </a>

          <a
            href=""
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Scaffold Repo &rarr;</h2>
            <p>
              View the repo.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
